### ISSUE TITLE
Hitman crash at launch [GLVND]

### ISSUE THREAD

**Issue by Fl0ux** [FeralInteractive/ferallinuxscripts#1]
Hello,

I cannot launch Hitman's Demo because it is crashing at lauch. All my other Feral's games are working fine, so this is not the usual libssl/libcrypto bug.

You will find attached some information on my system and a coredump. Let me know if you need additional information.

Thanks,

[crashes.zip](https://github.com/FeralInteractive/ferallinuxscripts/files/1121689/crashes.zip)

**Comment by mdiluz** [comment]
Hi @Fl0ux, judging from the output here I think the issue you're running into is caused by the Nvidia installer. It's triggered by installing the non-GLVND variant of the driver and is hit when an application creates both a GL and a Vk context.

Note the fix [here](https://devtalk.nvidia.com/default/topic/1016125/unix-graphics-announcements-and-news/-linux-solaris-and-freebsd-driver-384-47-beta-/) in the `384.47 (beta)` release:

> Fixed a bug where nvidia-installer would install a wrong version of the Vulkan ICD configuration file when GLVND is disabled for the GLX client.

We originally thought it was just a Debian packaging issue and reported it [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864477). It then showed up elsewhere so we reported directly to Nvidia.

I'm not sure the exact fix for OpenSUSE here, on Debian the simplest workaround was to install the `libgl1-nvidia-glvnd-glx` package alongside `libgl1-nvidia-glx`. On SUSE YaST should provide something similar.

Alternatively I'd suggest installing the `384.47 (beta)` release or replace your current driver `375.66` directly with the GLVND variant using the installer provided on the nvidia website.

Let us know if that works for you.

**Comment by mdiluz** [comment]
I'll assume this has been resolved and close the issue

**Comment by Fl0ux** [comment]
Actually Tumbleweed supports GLVND, but Leap does not yet. So there is no fix at moment and I guess I just have to wait...

**Comment by mdiluz** [comment]
Ah cheers, I'll re-open for now then

**Comment by Fl0ux** [comment]
The issue is now fixed by the last NVIDIA driver update.
