### ISSUE TITLE
F1 2017 doesn't open on GCN 1.0 card

### ISSUE THREAD

**Issue by amarildojr** [FeralInteractive/ferallinuxscripts#9]
Hi!

I just bought F1 2017 on Steam, but I can't run it.

I have a GCN 1.0 card (R9 270X), which Feral says it's not supported, but the game should run fine since I installed everything related to Vulkan/amdgpu and I'm running the amdgpu kernel driver on Debian Testing. Vulkan itself works on this card/kernel driver combo.

```
amarildo@amarildo:~$ lspci -vv | grep amdgpu 
Kernel driver in use: amdgpu 
Kernel modules: radeon, amdgpu
```

However, upon clicking "Play", the game doesn't open. There's nothing interesting in the Terminal:

`F12017: crash reporter initialised with path "/home/amarildo/.local/share/feral-interactive/F1 2017/crashes" SDL2 initialised [built against 2.0.5, running with 2.0.5]`

There's nothing in that folder.

I also installed LLVM 4, 5 and 6 (they can all exist in the same OS installation).

Any ideas?

Thanks!

```
amarildo@amarildo:~$ vulkaninfo | grep deviceName
WARNING: radv is not a conformant vulkan implementation, testing use only.
        deviceName     = AMD RADV PITCAIRN (LLVM 5.0.1)
```

**Comment by mdiluz** [comment]
Hi @amarildojr,

Sorry, but this issue isn't related to the launch scripts, it would be best to contact support@feralinteractive.com.

I would say however that GCN 1.0 cards were unsupported at the time of release due to more than just the kernel driver, so even if you get things working, there's may be graphical issues, crashes or other problems.
